### ISSUE TITLE
Import Error in Meteor

### ISSUE THREAD

**Issue by ignivalancy** [alekbarszczewski/graphql-schema-modules#1]
When i import 

> graphql-schema-modules

it shows 

![screen shot 2017-06-08 at 12 43 18 pm](https://user-images.githubusercontent.com/14292549/26916465-1da9b2c2-4c48-11e7-9270-699967ef6966.png)

**Comment by alekbarszczewski** [comment]
This package supports only Node.js >= 6.x because it uses 6.x features like `let { a, b } = ...`.

**Comment by ignivalancy** [comment]
i am using this with Meteor .

**Comment by ignivalancy** [comment]
do you have any idea how to use this with meteor.

**Comment by alekbarszczewski** [comment]
I am not familiar with meteor but I found this https://stackoverflow.com/questions/43876438/meteor-node-js-latest-version. It seems that for until meteor 1.6 is released you are forced to use Node.js 4.x :(. However there is some babel plugin for meteor (to enable ES6 features) - it is described here https://medium.com/@dferber90/es6-in-meteor-5e088c998e4a. I am not sure if will transpile also dependencies...

**Comment by ignivalancy** [comment]
Do you have any idea how we can use this with node v4.8.1

**Comment by ignivalancy** [comment]
mergeModules method .... working fine ... thanks
